id: PBF9B48A5
initial_creation_type: input
source_metadata:
  Title: Bhikṣuṇī Vinaya
  Editor: Gustav Roth
  Publisher: K.P.Jayaswal Research Institute
  Place of Publication: Patna
  Year: '1970'
  Bhikṣuṇī vinaya:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:15:38.411670'
last_modified_at: '2022-03-08T16:15:38.411681'
